### ISSUE TITLE
ReferenceError: require is not defined

### ISSUE THREAD

**Issue by sadiq-mc** [Esri/quickstart-map-phonegap#13] opened 2016-03-07 12:32 UTC
Map is not loading when I tried by adding this script 
`<script src="http://js.arcgis.com/3.14"></script>`
`<script src="assets/js/jQueryHelper.js"></script>`

**Comment by andygup** [comment] 2016-03-07 16:50
Are you using one of the sample applications? If not, please try one of the sample applications and let me know if you are seeing the same problem.

**Comment by sadiq-mc** [comment] 2016-03-07 19:05
Yes.. am using one of the examples..



On Mon, Mar 7, 2016 at 8:50 AM -0800, "Andy" <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you using one of the sample applications? If not, please try one of the sample applications and let me know if you are seeing the same problem.

-
Reply to this email directly or view it on GitHub<https://github.com/Esri/quickstart-map-phonegap/issues/13#issuecomment-193341089>.

IMPORTANT NOTICE: This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. The sender therefore does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission. If verification is required please request a hard-copy version.

**Comment by sadiq-mc** [comment] 2016-03-09 06:32
I am trying using the example **index_jquerymobilegps.html**

**Comment by andygup** [comment] 2016-03-15 18:11
Are you saying the unmodified sample app `index_jquerymobilegps.html` isn't working correctly? Can you please paste a screenshot of the console log?

**Comment by sadiqmc** [comment] 2016-03-16 04:50
The sample app is working fine... I said I used the same scripts mentioned above.

**Comment by andygup** [comment] 2016-03-16 15:56
If the sample app works on the device, then there is an issue with your custom code. 

Are you able to post your code and a screenshot of the console log?

**Comment by sadiqmc** [comment] 2016-03-18 12:56
I am using the same code mentioned in the comment [here](https://github.com/Esri/quickstart-map-phonegap/issues/14#issuecomment-197792654)

Instead of dojo.js am using the below script 
`<script src="http://js.arcgis.com/3.14"></script>`

**Comment by andygup** [comment] 2016-03-18 15:32
@sadiq-mc Sorry, I should have said it would be very helpful to see the entire application rather than just a snippet. 

**98%** of the time `require not defined` errors are caused by problems within the application's life-cycle. The only way to find those is to look at all the code in the app.

**Recommendation:** make sure to delay running the `require` until after Cordova's `deviceready` event has fired. Example: [basicmap.js](https://github.com/Esri/quickstart-map-phonegap/blob/master/scripts/basicmap.js#L17)

**Comment by sadiqmc** [comment] 2016-03-21 05:14
@andygup Just to mention, The `require` is invoked on map page load.. The script is invoked only at that time.. that means after `deviceready` is fired. The `deviceready` is called in index.js and the map's html & its javascript is invoked on a button click. 

Am using a bunch of scripts in index.html and and do this get any conflict with map script.???
Below are the scripts loaded in index.html

```
<script src="js/jquery.min.js"></script>
<script src="js/jquery.mobile-1.4.5.min.js"></script>
<script src="js/jquery-ui.min.js"></script>
<script src="js/inputmask.js"></script>
<script src="js/jquery.inputmask.js"></script>
<script type="text/javascript" charset="utf-8" src="phonegap.js"></script>
<script type="text/javascript" charset="utf-8"></script>
<script type="text/javascript" charset="utf-8" src="cordova.js"></script>

<!-- Custom scripts block -->
   ...........
<!-- Custom scripts ends -->
```

**Comment by andygup** [comment] 2016-03-21 16:07
**Recommendation 1:** remove the script tag for phonegap.js or the one for cordova.js. We don't recommend running both phonegap and cordova at the same time and in the same app.

**Recommendation 2:** Make sure to mimic the life-cycle demonstrated in the [jquery mobile sample](https://github.com/Esri/quickstart-map-phonegap/blob/master/index_jquerymobilegps_localarcgis.html). If you are following that sample, your application life-cycle will look like this PSUEDO-code:

```html
<head>
   jquery css
   esri css
   jquery library
   jquery mobile library
</head>
<body>
   HTML
   dojo.js
   jQueryHelper.js
   cordova.js
</body>
```

**Comment by andygup** [comment] 2016-03-29 17:08
@sadiq-mc any luck with this?

**Comment by sadiq-mc** [comment] 2016-03-30 05:23
Sorry Andy, I couldn't able to test this. :(

**Comment by andygup** [comment] 2016-03-30 14:12
Okay, I'm going to close this issue out. If you have new information that will help in troubleshooting then let us know.

**Closed by andygup** 2016-03-30 14:12 UTC

**Comment by sadiq-mc** [comment] 2016-03-31 04:56
Ok.. Will let you know the result once I test this case again.
